=== Gaalpos/marcas/aRECUPERACION/ExamenB/Soluciones/registro.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <!--registro es un grupo de personas CODIGO DADO-->
    <xs:element name="registro">
        <xs:complexType>
            <xs:sequence>
                <xs:group ref="personas"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!--un grupo de personas esta formado por usuarios
    y empleados CODIGO DADO-->
    <xs:group name="personas">
        <xs:sequence>
            <xs:element name="usuario" minOccurs="0" maxOccurs="unbounded" type="tipoUsuario"/>
            <xs:element name="empleado" minOccurs="0" maxOccurs="unbounded" type="tipoEmpleado"/>
        </xs:sequence>
    </xs:group>

   <xs:complexType name="tipoUsuario">
        <xs:sequence>
            <xs:element name="apellidos_nombre">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="[a-zA-Z ]{1,30},[a-zA-Z ]{1,20}"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="email">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="[a-z]{1,15}@[a-z]{1,25}[.][a-z]{2,4}"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="conexiones">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="conexion" minOccurs="0"
                                    maxOccurs="unbounded">
                            <xs:complexType>
                                <xs:simpleContent>
                                    <xs:extension base="xs:positiveInteger">
                                        <xs:attributeGroup ref="atributosConexion"/>
                                    </xs:extension>
                                </xs:simpleContent>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="identificador" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:pattern value="[UE]\d{1,5}"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>

    <xs:complexType name="tipoEmpleado">
        <xs:sequence>
            <xs:element name="apellidos_nombre">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="[a-zA-Z ]{1,30},[a-zA-Z ]{1,20}"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="email">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="[a-z]{1,15}@[a-z]{1,25}[.][a-z]{2,4}"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="conexiones">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="conexion" minOccurs="0"
                                    maxOccurs="unbounded">
                            <xs:complexType>
                                <xs:simpleContent>
                                    <xs:extension base="xs:positiveInteger">
                                        <xs:attributeGroup ref="atributosConexion"/>
                                    </xs:extension>
                                </xs:simpleContent>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="departamento">
                <xs:complexType>
                    <xs:choice>
                        <xs:element name="administración"/>
                        <xs:element name="informática"/>
                        <xs:element name="marketing"/>
                    </xs:choice>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="identificador" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:pattern value="[UE]\d{1,5}"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>

    <xs:attributeGroup name="atributosConexion">
        <xs:attribute name="fecha" type="xs:date" use="required"/>
        <xs:attribute name="hora" type="xs:time" use="required"/>
    </xs:attributeGroup>



</xs:schema>

=== Gaalpos/marcas/2021-2022/aRECUPERACION/ExamenB/Soluciones/registro.xml
<?xml version="1.0" encoding="UTF-8"?>
<registro xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="registro.xsd">

    <usuario identificador="U123">
        <apellidos_nombre>Sanz Tapia,Ana</apellidos_nombre>
        <email>asanz@jmail.com</email>

        <conexiones>
            <conexion fecha="2014-02-23" hora="19:15:40">122</conexion>
            <conexion fecha="2014-02-23" hora="20:30:22">617</conexion>
            <conexion fecha="2014-02-24" hora="11:18:31">25</conexion>
        </conexiones>

    </usuario>

    <usuario identificador="U96">
        <apellidos_nombre>Ruiz Hierro,Pedro</apellidos_nombre>
        <email>pruiz@jotmail.com</email>
        <conexiones>
            <conexion fecha="2014-02-25" hora="20:33:55">390</conexion>
        </conexiones>
    </usuario>

    <empleado identificador="E4">
        <apellidos_nombre>Vera Gil,Marta</apellidos_nombre>
        <email>mvera@yajoo.es</email>
        <conexiones/>
        <departamento>
            <marketing />
        </departamento>
    </empleado>
</registro>
