=== Gaalpos/marcas/2022-2023/Alejandro/XML/Apuntes/ejercicioDOCE.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="listado" type="tListado"/>

    <xs:complexType name="tListado">
        <xs:sequence>
            <xs:element name="futuro" type="tFuturo" maxOccurs="unbounded"/>
            <xs:element name="divisa" type="tDivisa" maxOccurs="unbounded"/>
            <xs:element name="bono" type="tBono" maxOccurs="unbounded"/>
            <xs:element name="letra" type="tLetra" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="tFuturo">
        <xs:sequence>
            <xs:element name="producto" type="xs:string"/>
            <xs:element name="mercado" type="xs:string"/>
            <xs:element name="ciudad_procedencia" type="tCiudad"/>
        </xs:sequence>
        <xs:attribute name="precio" type="xs:float" use="required"/>
    </xs:complexType>

    <xs:complexType name="tDivisa">
        <xs:sequence>
            <xs:element name="nombre_divisa" type="xs:string"/>
            <xs:element name="tipo_de_cambio" type="xs:string" maxOccurs="unbounded"/>
            <xs:element name="ciudad_procedencia" type="tCiudad"/>
        </xs:sequence>
        <xs:attribute name="precio" type="xs:float" use="required"/>
    </xs:complexType>

    <xs:complexType name="tBono">
        <xs:sequence>
            <xs:element name="pais_de_procedencia" type="xs:string"/>
            <xs:element name="valor_deseado" type="xs:int"/>
            <xs:element name="valor_minimo" type="xs:int"/>
            <xs:element name="valor_maximo" type="xs:int"/>
            <xs:element name="ciudad_procedencia" type="tCiudad"/>
        </xs:sequence>
        <xs:attribute name="precio" type="xs:float" use="required"/>
        <xs:attribute name="estable" type="xs:string" use="optional"/>
    </xs:complexType>

    <xs:complexType name="tLetra">
        <xs:sequence>
            <xs:element name="tipo_de_interes" type="xs:string"/>
            <xs:element name="pais_emisor" type="tPais"/>
            <xs:element name="ciudad_procedencia" type="tCiudad"/>
        </xs:sequence>
        <xs:attribute name="precio" type="xs:float" use="required"/>.
    </xs:complexType>

    <xs:complexType name="tEmpty"/>

    <xs:complexType name="tCiudad">
        <xs:choice>
            <xs:element name="madrid" type="tEmpty"/>
            <xs:element name="frankfurt" type="tEmpty"/>
            <xs:element name="tokio" type="tEmpty"/>
        </xs:choice>
    </xs:complexType>

    <xs:complexType name="tPais">
        <xs:choice>
            <xs:element name="espania" type="tEmpty"/>
        </xs:choice>
    </xs:complexType>
</xs:schema>

=== Gaalpos/marcas/2022-2023/Alejandro/XML/Apuntes/ejercicioDOCE.xml
<?xml version="1.0" encoding="UTF-8" ?>
<listado xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="ejercicioDOCE.xsd">
    <futuro precio="11.28">
        <producto>Cafe</producto>
        <mercado>América Latina</mercado>
        <ciudad_procedencia>
            <frankfurt/>
        </ciudad_procedencia>
    </futuro>
    <divisa precio="183">
        <nombre_divisa>Libra esterlina</nombre_divisa>
        <tipo_de_cambio>2.7:1 euros</tipo_de_cambio>
        <tipo_de_cambio>1:0.87 dólares</tipo_de_cambio>
        <ciudad_procedencia>
            <madrid/>
        </ciudad_procedencia>
    </divisa>
    <bono precio="10000" estable="si">
        <pais_de_procedencia>
            Islandia
        </pais_de_procedencia>
        <valor_deseado>9980</valor_deseado>
        <valor_minimo>9950</valor_minimo>
        <valor_maximo>10020</valor_maximo>
        <ciudad_procedencia>
            <tokio/>
        </ciudad_procedencia>
    </bono>
    <letra precio="45020">
        <tipo_de_interes>4.54%</tipo_de_interes>
        <pais_emisor>
            <espania/>
        </pais_emisor>
        <ciudad_procedencia>
            <madrid/>
        </ciudad_procedencia>
    </letra>
</listado>
