=== Gaalpos/marcas/2022-2023/Alejandro/XML/Examen/ejercicio1A.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:element name="hitchcock" type="tHitchcock"/>

    <xsd:complexType name="tHitchcock">
        <xsd:sequence>
            <xsd:element name="estudios" type="tEstudios"/>
            <xsd:element name="actores" type="tActores"/>
            <xsd:element name="peliculas" type="tPeliculas"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="tEstudios">
        <xsd:sequence>
            <xsd:element name="estudio" type="tEstudio" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="tEstudio">
        <xsd:sequence>
            <xsd:element name="nombre" type="xsd:string"/>
            <xsd:element name="fecha" type="tFecha"/>
        </xsd:sequence>
        <xsd:attribute name="id" type="xsd:string" use="required"/>
    </xsd:complexType>

    <xsd:complexType name="tFecha">
        <xsd:simpleContent>
            <xsd:extension base="xsd:string">
                <xsd:attribute name="dato" use="required"/>
            </xsd:extension>
        </xsd:simpleContent>
    </xsd:complexType>

    <xsd:complexType name="tActores">
        <xsd:sequence>
            <xsd:element name="actor" type="tActor" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="tActor">
        <xsd:simpleContent>
            <xsd:extension base="xsd:string">
                <xsd:attribute name="nombre" use="required"/>
                <xsd:attribute name="nacimiento" use="required"/>
                <xsd:attribute name="muerte" use="optional"/>
            </xsd:extension>
        </xsd:simpleContent>

    </xsd:complexType>

    <xsd:complexType name="tPeliculas">
        <xsd:sequence>
            <xsd:element name="pelicula" type="tPelicula" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="tPelicula">
        <xsd:sequence>
            <xsd:element name="titulo" type="tTitulo" maxOccurs="unbounded"/>
            <xsd:element name="fecha" type="tFecha"/>
            <xsd:element name="estudios" type="tEstudios2"/>
            <xsd:element name="oscar" type="tOscar"/>
            <xsd:element name="actores" type="tActores2"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="tTitulo">
        <xsd:simpleContent>
            <xsd:extension base="xsd:string">
                <xsd:attribute name="lang" use="required"/>
            </xsd:extension>
        </xsd:simpleContent>
    </xsd:complexType>

    <xsd:complexType name="tEstudios2">
        <xsd:simpleContent>
            <xsd:extension base="xsd:string">
                <xsd:attribute name="nombre" type="xsd:string" use="required"/>
            </xsd:extension>
        </xsd:simpleContent>
    </xsd:complexType>

    <xsd:complexType name="tOscar">
        <xsd:attribute name="nominaciones" type="xsd:int" use="required"/>
        <xsd:attribute name="premios" type="xsd:int" use="required"/>
    </xsd:complexType>

    <xsd:complexType name="tActores2">
        <xsd:sequence>
            <xsd:element name="actor" type="xsd:string"/>
            <xsd:element name="actriz" type="xsd:string"/>
        </xsd:sequence>
    </xsd:complexType>
</xsd:schema>

=== Gaalpos/marcas/2022-2023/Alejandro/XML/Apuntes/ejercicio1A.xml
<?xml version="1.0" encoding="UTF-8"?>
<hitchcock xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="ejercicio1A.xsd">

    <estudios>
        <estudio id="warner">
            <nombre>Warner Bros.</nombre>
            <fecha dato="nacimiento">1923</fecha>
        </estudio>
        <estudio id="paramount">
            <nombre>Paramount Pictures</nombre>
            <fecha dato="nacimiento">1914</fecha>
        </estudio>
    </estudios>

    <actores>
        <actor nombre="James Stewart" nacimiento="1908" muerte="1997" />
        <actor nombre="Grace Kelly" nacimiento="1929" muerte="1982" />
        <actor nombre="Farley Granger" nacimiento="1925" muerte="2011" />
        <actor nombre="Ruth Roman" nacimiento="1922" muerte="1999" />
        <actor nombre="Kim Novack" nacimiento="1933" muerte="" />
        <actor nombre="Anthony Perkins" nacimiento="1932" muerte="1992" />
        <actor nombre="Vera Miles" nacimiento="1929" muerte="" />
    </actores>

    <peliculas>
        <pelicula>
            <titulo lang="es">La ventana indiscreta</titulo>
            <titulo lang="en">Rear Window</titulo>
            <fecha dato="estreno">1954</fecha>
            <estudios nombre="paramount" />
            <oscar nominaciones="4" premios="0" />
            <actores>
                <actor>James Stewart</actor>
                <actriz>Grace Kelly</actriz>
            </actores>
        </pelicula>

        <pelicula>
            <titulo lang="es">Extraños en un tren</titulo>
            <titulo lang="en">Strangers on a Train</titulo>
            <fecha dato="estreno">1951</fecha>
            <estudios nombre="warner" />
            <oscar nominaciones="1" premios="0" />
            <actores>
                <actor>Farley Granger</actor>
                <actriz>Ruth Roman</actriz>
            </actores>
        </pelicula>

        <pelicula>
            <titulo lang="es">Vértigo</titulo>
            <titulo lang="en">Vertigo</titulo>
            <fecha dato="estreno">1958</fecha>
            <estudios nombre="paramount" />
            <oscar nominaciones="2" premios="0" />
            <actores>
                <actor>James Stewart</actor>
                <actriz>Kim Novack</actriz>
            </actores>
        </pelicula>

        <pelicula>
            <titulo lang="es">Psicosis</titulo>
            <titulo lang="en">Psycho</titulo>
            <fecha dato="estreno">1960</fecha>
            <estudios nombre="paramount" />
            <oscar nominaciones="4" premios="0" />
            <actores>
                <actor>Anthony Perkins</actor>
                <actriz>Vera Miles</actriz>
            </actores>
        </pelicula>
    </peliculas>
</hitchcock>
